---
- name: Debian | Add keys authenticity
  apt_key: 
    url: http://keyserver.ubuntu.com/pks/lookup?op=get&search=0x7F0CEB10 
    id: 7F0CEB10

- name: Debian | Add source sources
  apt_repository: 
    repo: 'deb http://downloads-distro.mongodb.org/repo/debian-sysvinit dist 10gen'
    update_cache: yes

- name: Debian | Install Packages
  apt:
    pkg: "{{ item }}"
    state: latest
  with_items:
    - python-pymongo
    - mongodb-org

- name: Start mongodb
  service: 
    name: mongod
    state: started 
    enabled: yes

- name: set admin password
  mongodb_user:
    database: "admin"
    name: "admin"
    password: "{{ admin_password }}"
    roles: root
    state: present

- name: Copy the mongod.conf file 
  template: 
    src: mongod.conf.j2
    dest: /etc/mongod.conf

- name: Restart mongodb
  service: 
    name: mongod
    state: restarted 
    enabled: yes

- name: Create Database
  shell: echo use "{{ item.name }}" | mongo -u admin -p "{{ admin_password }}" --authenticationDatabase "admin"
  with_items:
    - "{{ mongo_db }}"

- mongodb_user:
    login_user: "admin"
    login_password: "{{ admin_password }}" 
    database: "{{ item.name }}"
    name: "{{ item.user }}"
    password: "{{ item.pass }}"
    state: present
  with_items:
    - "{{ mongo_db }}"
