---
- name: install libselinux-python binary for Ansible to work
  yum:
    name: libselinux-python
    state: present
  when: ansible_distribution in ['CentOS', 'Red Hat Enterprise Linux']

- name: install libselinux-python binary for Ansible to work
  apt:
    name: python-selinux
    state: present
  when: ansible_distribution in ['Debian', 'Ubuntu']

- name: create Prometheus group
  group:
    name: prometheus
    state: present

- name: create Prometheus user
  user:
    name: prometheus
    group: prometheus
    createhome: yes
    home: /opt/prometheus
    shell: /sbin/nologin
    comment: "Prometheus User"
    state: present

- name: mkdir for general cases
  file:
    path: "{{ item }}"
    state: directory
    owner: prometheus
    group: prometheus
    recurse: yes
    mode: 0740
  with_items:
    - /opt/prometheus
    - /etc/prometheus
    - /etc/prometheus/rules
    - /var/log/prometheus
    - /var/run/prometheus
    - /data/prometheus

- name: download gosu executable
  get_url:
    url: "https://github.com/tianon/gosu/releases/download/1.10/gosu-amd64"
    dest: "/usr/local/bin/gosu"
  when: ansible_architecture == 'x86_64'

- name: download gosu executable
  get_url:
    url: "https://github.com/tianon/gosu/releases/download/1.10/gosu-armhf"
    dest: "/usr/local/bin/gosu"
  when: ansible_architecture == 'armv7l' or ansible_architecture == 'armv6l'

- name: add executable permission
  file:
    path: "/usr/local/bin/gosu"
    state: file
    mode: "a+x"

- name: download and untar prometheus tarball
  unarchive:
    src: "https://github.com/prometheus/prometheus/releases/download/v{{ prometheus.version }}/prometheus-{{ prometheus.version }}.linux-amd64.tar.gz"
    dest: /opt/prometheus
    creates: /opt/prometheus/prometheus-{{ prometheus.version }}.linux/prometheus
    owner: prometheus
    group: prometheus
    mode: 0740
    copy: no
  when: ansible_architecture == 'x86_64'
  notify:
    - restart prometheus

- name: download and untar prometheus tarball
  unarchive:
    src: "https://github.com/prometheus/prometheus/releases/download/v{{ prometheus.version }}/prometheus-{{ prometheus.version }}.linux-armv7.tar.gz"
    dest: /opt/prometheus
    creates: /opt/prometheus/prometheus-{{ prometheus.version }}.linux/prometheus
    owner: prometheus
    group: prometheus
    mode: 0740
    copy: no
  when: ansible_architecture == 'armv7l'
  notify:
    - restart prometheus

- file:
    src: /opt/prometheus/prometheus-{{ prometheus.version }}.linux-amd64
    dest: /opt/prometheus/prometheus-{{ prometheus.version }}.linux
    owner: prometheus
    group: prometheus
    state: link
  when: ansible_architecture == 'x86_64'

- file:
    src: /opt/prometheus/prometheus-{{ prometheus.version }}.linux-armv7
    dest: /opt/prometheus/prometheus-{{ prometheus.version }}.linux
    owner: prometheus
    group: prometheus
    state: link
  when: ansible_architecture == 'armv7l'

- name: Copy prometheus configuration
  template:
    src: "{{ prometheus.configuration_template | default('prometheus.yml.j2') }}"
    dest: /etc/prometheus/prometheus.yml
    owner: prometheus
    group: prometheus
    mode: 0740
  notify:
    - restart prometheus

- name: Copy prometheus configuration
  copy:
    src: "{{ prometheus.rules_template }}"
    dest: /etc/prometheus/rules
    owner: prometheus
    group: prometheus
    directory_mode: yes
  when: prometheus.rules_template is defined
  notify:
    - reload prometheus

- name: Create Unit file prometheus
  template:
    src: prometheus.service.j2
    dest: /etc/systemd/system/prometheus.service
    mode: 0640
  notify:
    - reload systemctl
    - restart prometheus

- name: Start prometheus
  service:
    name: prometheus.service
    state: started
    enabled: yes
