- name : install xfsprogs
  yum:
    name: xfsprogs
    update_cache: yes
    state: latest
  when: filesystem_enable == True

- name: format fs
  filesystem:
    dev: "{{ item.dev }}"
    fstype: "{{ item.fstype }}"
  when: filesystem_enable == True
  with_items:
    - "{{ filesystem }}"

- name: mkdir for each mount
  file:
    path: "{{ item.path }}"
    state: directory
    recurse: yes
  when: filesystem_enable == True
  with_items:
    - "{{ mount }}"

- name: Set authorized key took from vars
  mount:
    src: "{{ item.src }}"
    path: "{{ item.path }}"
    fstype: "{{ item.fstype }}"
    state: "{{ item.state }}"
    opts: "{{ item.opts }}"
  when: filesystem_enable == True
  with_items:
    - "{{ mount }}"
