---
- group:
    name: openvpn
    state: present

- user:
    name: openvpn
    shell: /bin/false
    groups: openvpn
    append: yes

- name: install
  yum:
    name: 'openvpn'
    update_cache: yes
    state: latest
  when: ansible_distribution in ['CentOS', 'Red Hat Enterprise Linux']

- name: install
  apt:
    name: 'openvpn'
    update_cache: yes
    state: latest
  when: ansible_distribution in ['Debian', 'Ubuntu']

- import_tasks: ssl.yml


- name: Copy openvpn server configuration in place.
  template:
    src: "{{ openvpn.configuration_template | default('server.conf.j2') }}"
    dest: /etc/openvpn/server.conf
    mode: 0644
  notify: restart openvpn
  when: openvpn.mode == "server"

- name: Copy openvpn client configuration in place.
  template:
    src: "{{ openvpn.configuration_template | default('client.conf.j2') }}"
    dest: /etc/openvpn/client.conf
    mode: 0644
  notify: restart openvpn
  when: openvpn.mode == "client"

- import_tasks: ccd.yml
  when: openvpn.mode == "server"

- name: Ensure openvpn is started and enabled on boot.
  service:
    name: "openvpn@{{ openvpn.mode }}.service"
    state: started
    enabled: yes
