---
- group:
    name: openvpn
    state: present

- user:
    name: openvn
    shell: /bin/false
    groups: openvpn
    append: yes

- name: Ensure openvpn is installed
  yum:
    name: openvpn
    state: installed

- include: ssl.yml

- name: Copy openvpn configuration in place.
  template:
    src: "{{ openvpn.configuration_template | default('server.conf.j2') }}"
    dest: /etc/openvpn/server.conf
    mode: 0644
  notify: restart openvpn

- name: Ensure openvpn is started and enabled on boot.
  service:
    name: openvpn@server.service
    state: started
    enabled: yes
