- name: create directory for PEM files
  file:
    path: /etc/openvpn/ssl
    owner: openvpn
    group: openvpn
    mode: 0600
    state: directory

- name: Copy dh key files
  copy:
    dest: "/etc/openvpn/ssl/dh.pem"
    content: "{{ openvpn.dh }}"
    owner: openvpn
    group: openvpn
    mode: 0600
  notify: restart openvpn
