---
- name: Import openhab2 key
  rpm_key:
    key: https://openhab.jfrog.io/openhab/openhab-linuxpkg-rpm/stable/repodata/repomd.xml.key
    state: present
  when: ansible_distribution in ['CentOS', 'Red Hat Enterprise Linux', 'Fedora']

- name: add openhab2 repo
  yum_repository:
    name: openhab2
    description: openhab2 repo
    baseurl: https://openhab.jfrog.io/openhab/openhab-linuxpkg-rpm/stable
  when: ansible_distribution in ['CentOS', 'Red Hat Enterprise Linux', 'Fedora']

- name: Ensure openhab2 is installed
  yum:
    name: 
        - openhab2
        - openhab2-addons
        - java-1.8.0-openjdk
    state: installed

- name: Create /etc/default/openhab2
  template:
    src: openhab2.j2
    dest: /etc/default/openhab2
  notify:
    - restart_openhab

- name: Create addons.cfg
  template:
    src: addons.cfg.j2
    dest: /etc/openhab2/services/addons.cfg
    owner: openhab
    group: openhab
  notify:
    - restart_openhab

- service:
    name: openhab2
    state: started
    enabled: yes
