---
- name: Install package node_exporter
  pkgng:
    name: node_exporter
    state: present

- name: Ensure collector.devstat is enable
  lineinfile:
    state: present
    path: /etc/rc.conf
    line: 'node_exporter_args="--collector.devstat"'

- name: enable node_exporter
  service: 
    name: node_exporter 
    state: started 
    enabled: yes
