---
- name: install libselinux-python binary for Ansible to work
  yum:
    name: libselinux-python
    state: present
  when: ansible_distribution in ['CentOS', 'Red Hat Enterprise Linux']

- name: install libselinux-python binary for Ansible to work
  apt:
    name: python-selinux
    state: present
  when: ansible_distribution in ['Debian'] and ansible_distribution_major_version <= "10"

- name: install libselinux-python binary for Ansible to work
  apt:
    name: python3-selinux
    state: present
  when: ansible_distribution in ['Debian'] and ansible_distribution_major_version >= "11"

- name: create Prometheus group
  group:
    name: prometheus
    state: present

- name: create Prometheus user
  user:
    name: prometheus
    group: prometheus
    createhome: yes
    home: /opt/prometheus
    shell: /sbin/nologin
    comment: "Prometheus User"
    state: present

- name: mkdir for general cases
  file:
    path: "{{ item }}"
    state: directory
    owner: prometheus
    group: prometheus
    recurse: yes
    mode: 0740
  with_items:
    - /opt/node_exporter
    - /etc/node_exporter
    - /var/log/node_exporter
    - /var/run/node_exporter
    - /var/tmp/node_exporter

- name: download gosu executable
  get_url:
    url: "https://github.com/tianon/gosu/releases/download/1.10/gosu-amd64"
    dest: "/usr/local/bin/gosu"
  when: ansible_architecture == 'x86_64'

- name: download gosu executable
  get_url:
    url: "https://github.com/tianon/gosu/releases/download/1.10/gosu-armhf"
    dest: "/usr/local/bin/gosu"
  when: ansible_architecture == 'armv7l' or ansible_architecture == 'armv6l'

- name: add executable permission
  file:
    path: "/usr/local/bin/gosu"
    state: file
    mode: "a+x"

- name: download and untar node_exporter tarball
  unarchive:
    src: "https://github.com/prometheus/node_exporter/releases/download/v0.18.1/node_exporter-0.18.1.linux-amd64.tar.gz"
    dest: /opt/node_exporter
    creates: /opt/node_exporter/node_exporter-0.18.1.linux/node_exporter
    owner: prometheus
    group: prometheus
    mode: 0740
    copy: no
  when: ansible_architecture == 'x86_64'
  notify:
    - restart node_exporter

- name: download and untar node_exporter tarball
  unarchive:
    src: "https://github.com/prometheus/node_exporter/releases/download/v0.18.1/node_exporter-0.18.1.linux-armv7.tar.gz"
    dest: /opt/node_exporter
    creates: /opt/node_exporter/node_exporter-0.18.1.linux/node_exporter
    owner: prometheus
    group: prometheus
    mode: 0740
    copy: no
  when: ansible_architecture == 'armv7l'
  notify:
    - restart node_exporter

- name: download and untar node_exporter tarball
  unarchive:
    src: "https://github.com/prometheus/node_exporter/releases/download/v0.18.1/node_exporter-0.18.1.linux-armv6.tar.gz"
    dest: /opt/node_exporter
    creates: /opt/node_exporter/node_exporter-0.18.1.linux/node_exporter
    owner: prometheus
    group: prometheus
    mode: 0740
    copy: no
  when: ansible_architecture == 'armv6l'
  notify:
    - restart node_exporter

- file:
    src: /opt/node_exporter/node_exporter-0.18.1.linux-amd64
    dest: /opt/node_exporter/node_exporter-0.18.1.linux
    owner: prometheus
    group: prometheus
    state: link
  when: ansible_architecture == 'x86_64'

- file:
    src: /opt/node_exporter/node_exporter-0.18.1.linux-armv7
    dest: /opt/node_exporter/node_exporter-0.18.1.linux
    owner: prometheus
    group: prometheus
    state: link
  when: ansible_architecture == 'armv7l'

- file:
    src: /opt/node_exporter/node_exporter-0.18.1.linux-armv6
    dest: /opt/node_exporter/node_exporter-0.18.1.linux
    owner: prometheus
    group: prometheus
    state: link
  when: ansible_architecture == 'armv6l'

- name: Create Unit file node_exporter
  template:
    src: node_exporter.service.j2
    dest: /etc/systemd/system/node_exporter.service
    mode: 0640
  notify:
    - restart node_exporter
    - reload systemctl

- name: Start node_exporter
  service:
    name: node_exporter.service
    state: started
    enabled: yes
