---
- name: Import epel key
  rpm_key:
    key: http://epel.mirrors.ovh.net/epel/RPM-GPG-KEY-EPEL-7
    state: present
    validate_certs: no
  when: ansible_distribution in ['CentOS', 'Red Hat Enterprise Linux', 'Fedora']

- name: add epel repo
  yum_repository:
    name: epel
    description: epel
    mirrorlist: https://mirrors.fedoraproject.org/metalink?repo=epel-7&arch=$basearch
  when: ansible_distribution in ['CentOS', 'Red Hat Enterprise Linux', 'Fedora']

- name: add epel-debuginfo repo
  yum_repository:
    name: epel-debuginfo
    description: epel
    mirrorlist: https://mirrors.fedoraproject.org/metalink?repo=epel-debug-7&arch=$basearch
  when: ansible_distribution in ['CentOS', 'Red Hat Enterprise Linux', 'Fedora']

- name: add epel-source repo
  yum_repository:
    name: epel-source
    description: epel
    mirrorlist: https://mirrors.fedoraproject.org/metalink?repo=epel-source-7&arch=$basearch
  when: ansible_distribution in ['CentOS', 'Red Hat Enterprise Linux', 'Fedora']

- name: Install common tools
  apt: 
    name: "{{ item }}" 
    state: latest 
    update_cache: yes
  with_items:
    - lsof
    - man
    - iotop
    - stress
    - git
    - vim
    - gcc
    - htop
    - tcpdump
    - strace
    - nmap
    - apt-transport-https
    - iperf
  when: ansible_distribution in ['Debian', 'Ubuntu']

- name: Install common tools
  yum: 
    name: "{{ item }}" 
    state: latest 
    update_cache: yes
  with_items:
    - git
    - vim
    - gcc
    - htop
    - tcpdump
    - strace
    - nmap
    - lsof
    - man
    - iotop
    - iperf
    - stress
    - libselinux-python
  when: ansible_distribution in ['CentOS', 'Red Hat Enterprise Linux', 'Fedora']


- name: upgrade all packages
  yum:
    name: '*'
    update_cache: yes
    state: latest
  when: ansible_distribution in ['CentOS', 'Red Hat Enterprise Linux', 'Fedora']


- name: Update all packages to the latest version
  apt:
    upgrade: yes
  when: ansible_distribution in ['Debian', 'Ubuntu']


- name: set hostname
  hostname:
    name: "{{ inventory_hostname}}"
