---
- name: Import epel key
  rpm_key:
    key: https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-7
    state: present
    validate_certs: no
  when: ansible_distribution in ['CentOS', 'Red Hat Enterprise Linux']

- name: add epel repo
  yum_repository:
    name: epel
    description: epel
    mirrorlist: https://mirrors.fedoraproject.org/metalink?repo=epel-7&arch=$basearch
  when: ansible_distribution in ['CentOS', 'Red Hat Enterprise Linux']

- name: add epel-debuginfo repo
  yum_repository:
    name: epel-debuginfo
    description: epel
    mirrorlist: https://mirrors.fedoraproject.org/metalink?repo=epel-debug-7&arch=$basearch
  when: ansible_distribution in ['CentOS', 'Red Hat Enterprise Linux']

- name: add epel-source repo
  yum_repository:
    name: epel-source
    description: epel
    mirrorlist: https://mirrors.fedoraproject.org/metalink?repo=epel-source-7&arch=$basearch
  when: ansible_distribution in ['CentOS', 'Red Hat Enterprise Linux']

- name: Install common tools
  apt: 
    state: latest 
    update_cache: yes
    name:
    - lsof
    - man
    - iotop
    - stress
    - git
    - vim
    - gcc
    - htop
    - tcpdump
    - strace
    - nmap
    - apt-transport-https
    - iperf
    - unzip
    - python-apt
  when: ansible_distribution in ['Debian', 'Ubuntu']

- name: Install common tools
  yum: 
    state: latest 
    update_cache: yes
    name: 
    - git
    - vim
    - gcc
    - htop
    - tcpdump
    - strace
    - nmap
    - lsof
    - man
    - iotop
    - iperf
    - stress
    - libselinux-python
    - unzip
    - wget
    - net-tools
    - python 
    - python-pip
  when: ansible_distribution in ['CentOS', 'Red Hat Enterprise Linux']

- name: Install common tools
  dnf: 
    state: latest 
    name:
    - git
    - vim
    - gcc
    - htop
    - tcpdump
    - strace
    - nmap
    - lsof
    - man
    - iotop
    - iperf
    - stress
    - python3-libselinux
    - unzip
    - tar
  when: ansible_distribution in ['Fedora']


- name: upgrade all packages
  yum:
    name: '*'
    update_cache: yes
    state: latest
  when: ansible_distribution in ['CentOS', 'Red Hat Enterprise Linux']

- name: upgrade all packages
  dnf:
    name: '*'
    state: latest
  when: ansible_distribution in ['Fedora']


- name: Update all packages to the latest version
  apt:
    upgrade: True
  when: ansible_distribution in ['Debian', 'Ubuntu']


- name: set hostname
  hostname:
    name: "{{ inventory_hostname}}"

- name: Disable SELinux
  selinux:
    state: disabled
  when: ansible_distribution in ['CentOS', 'Red Hat Enterprise Linux']
