- name: Packages python2.7
  apt:
    pkg: "{{ item }}"
    state: latest
  with_items:
    - python-setuptools
    - python-dev
    - libffi-dev
    - zlib1g-dev
    - libjpeg62-turbo-dev
    - libssl-dev

- name: install pip 
  easy_install:
    name: pip
    state: latest
    executable: easy_install-2.7

- name : Install common python2.7 tools with pip
  pip: 
    name: "{{ item }}"
    state: latest
    executable: pip2.7
  with_items:
    - setuptools
    - virtualenv
    - virtualenvwrapper

