---
- name: Import influxdb key
  rpm_key:
    key: https://repos.influxdata.com/influxdb.key
    state: present
    validate_certs: no
  when: ansible_distribution in ['CentOS', 'Red Hat Enterprise Linux', 'Fedora']

- name: add influxdb repo
  yum_repository:
    name: influxdb repo
    description: influxdb repo
    baseurl: https://repos.influxdata.com/rhel/$releasever/$basearch/stable
  when: ansible_distribution in ['CentOS', 'Red Hat Enterprise Linux', 'Fedora']

- name: Ensure influxdb is installed
  yum:
    name: influxdb
    state: installed

- service:
    name: influxdb
    state: started
    enabled: yes
