---
- name: mysql Add key
  apt_key: 
    url: http://keyserver.ubuntu.com/pks/lookup?op=get&search=0x5072E1F5 
    id: 5072E1F5

- name: Repo debian
  apt_repository:
    repo: deb http://repo.mysql.com/apt/debian/ jessie mysql-5.7
    state: present

- name: Install the mysql packages in Debian derivatives
  apt: 
    name: "{{ item }}" 
    state: latest 
    update_cache: yes 
  with_items:
    - python-selinux
    - python-mysqldb
    - mysql-server
    - libmysqlclient-dev

- name: Copy the my.cnf file 
  template: 
    src: my.cnf.j2 
    dest: /etc/mysql/my.cnf

- name: Start the mysql services
  service: 
    name: mysql 
    state: started 
    enabled: yes

- name: copy .my.cnf file with root password credentials
  template: 
    src: .my.cnf.j2 
    dest: ~/.my.cnf 
    mode: 0600

- name: update mysql root password for all root accounts
  mysql_user: 
    name: root 
    host: "{{ item }}" 
    password: "{{ mysql_root_db_pass }}"
  with_items:
   - "{{ ansible_hostname }}"
   - 127.0.0.1
   - ::1
   - localhost
   - 0.0.0.0
  when: ansible_hostname != 'localhost' 

- name: ensure anonymous users are not in the database
  mysql_user: 
    name: '' 
    host: "{{ item }}" 
    state: absent
  with_items:
   - localhost
   - "{{ ansible_hostname }}"

- name: remove the test database
  mysql_db: 
    name: test 
    state: absent

- name: Create a new database with name "{{ item.name }}"
  mysql_db:
    name: "{{ item.name }}"
    state: present
  with_items:
    - "{{ mysql_db }}"

- name: Create the database users
  mysql_user: 
    name: "{{ item.user }}"  
    password: "{{ item.pass }}" 
    priv: "{{ item.priv }}" 
    host: "{{ item.host }}"
    state: present 
  with_items: 
    - "{{ mysql_db }}"

- name: Start the mysql services
  service: 
    name: mysql 
    state: restarted
