---
- name: install libselinux-python binary for Ansible to work
  yum:
    name: "{{ item }}"
    state: present
  when: ansible_distribution in ['CentOS', 'Red Hat Enterprise Linux']
  with_items:
      - libselinux-python
      - java-1.8.0-openjdk
      - git 
      - python-twisted-core 
      - python-psutil 
      - python-urwid 
      - python-twisted-web

- name: create spigot group
  group:
    name: spigot
    state: present

- name: create spigot user
  user:
    name: spigot
    group: spigot
    createhome: yes
    home: /opt/spigot
    shell: /sbin/nologin
    comment: "spigot User"
    state: present

- name: mkdir for general cases
  file:
    path: "{{ item }}"
    state: directory
    owner: spigot
    group: spigot
    recurse: yes
    mode: 0740
  with_items:
    - /opt/spigot-{{ spigot.version }}
    - /opt/spigot-{{ spigot.version }}/mcrcon
    - /opt/spigot-{{ spigot.version }}/plugins
    - /opt/spigot-{{ spigot.version }}/plugins/PrometheusExporter


- name: download and untar mcrcon tarball
  unarchive:
    src: "https://github.com/Tiiffi/mcrcon/releases/download/v0.7.1/mcrcon-0.7.1-linux-x86-64.tar.gz"
    dest: /opt/spigot/
    owner: spigot
    group: spigot
    mode: 0740
    copy: no
  when: ansible_architecture == 'x86_64'

- name: download spigot jar
  get_url:
    url: "https://cdn.getbukkit.org/spigot/spigot-{{ spigot.version }}.jar"
    dest: /opt/spigot-{{ spigot.version }}/spigot.jar
    owner: spigot
    group: spigot
    mode: 0740
  notify:
    - restart spigot

- name: download papermc jar
  get_url:
    url: "https://papermc.io/api/v1/paper/{{ spigot.version }}/latest/download"
    dest: /opt/spigot-{{ spigot.version }}/paper.jar
    owner: spigot
    group: spigot
    mode: 0740
  notify:
    - restart spigot

- name: download plugin prometheus
  get_url:
    url: "https://github.com/sladkoff/minecraft-prometheus-exporter/releases/download/v2.0.1/minecraft-prometheus-exporter-2.0.1.jar"
    dest: "/opt/spigot-{{ spigot.version }}/plugins/"
    owner: spigot
    group: spigot
    mode: 0740
  notify:
    - restart spigot

- name: push pre validate eula
  template:
    src: eula.txt.j2
    dest: "/opt/spigot-{{ spigot.version }}/eula.txt"
    mode: 0640
    owner: spigot
    group: spigot   
  notify:
    - restart spigot

- name: server properties
  template:
    src: server.properties.j2
    dest: "/opt/spigot-{{ spigot.version }}/server.properties"
    mode: 0640
    owner: spigot
    group: spigot  
  notify:
    - restart spigot

- name: config prometheus plugin
  copy:
    content: "{{ spigot.plugin_prometheus | to_nice_yaml }}"
    dest: "/opt/spigot-{{ spigot.version }}/plugins/PrometheusExporter/config.yml"
    mode: 0640
    owner: spigot
    group: spigot
  notify:
    - restart spigot

- name: Create Unit file spigot
  template:
    src: spigot.service.j2
    dest: /etc/systemd/system/spigot.service
    mode: 0640
  notify:
    - restart spigot
    - reload systemctl

- name: Start spigot
  service:
    name: spigot.service
    state: started
    enabled: yes

- name: save-all every 20 minutes
  cron:
    name: "save_spigot"
    state: present
    minute: "1"
    job: "/opt/spigot/mcrcon-0.7.1-linux-x86-64/mcrcon -p {{ spigot.server_properties['rcon.password'] }} save-all"
