---
- name: install libselinux-python binary for Ansible to work
  yum:
    name: "{{ item }}"
    state: present
  when: ansible_distribution in ['CentOS', 'Red Hat Enterprise Linux']
  with_items:
      - libselinux-python
      - java-1.8.0-openjdk
      - git 
      - python-twisted-core 
      - python-psutil 
      - python-urwid 
      - python-twisted-web

- name: install libselinux-python binary for Ansible to work
  apt:
    name: "{{ item }}"
    state: present
  when: ansible_distribution in ['Debian']
  with_items:
      - python3-selinux
      - python3-apt
      - openjdk-17-jdk-headless
      - git 
      - python3-twisted 
      - python3-psutil 
      - python3-urwid 

- name: create spigot group
  group:
    name: spigot
    state: present

- name: create spigot user
  user:
    name: spigot
    group: spigot
    createhome: yes
    home: /opt/spigot
    shell: /sbin/nologin
    comment: "spigot User"
    state: present

- name: mkdir for general cases
  file:
    path: "{{ item }}"
    state: directory
    owner: spigot
    group: spigot
    recurse: yes
    mode: 0740
  with_items:
    - /opt/spigot-{{ spigot.version }}
    - /opt/spigot-{{ spigot.version }}/mcrcon
    - /opt/spigot-{{ spigot.version }}/plugins
    - /opt/spigot-{{ spigot.version }}/plugins/PrometheusExporter
    - /opt/spigot/backup

- name: download and untar mcrcon tarball
  unarchive:
    src: "https://github.com/Tiiffi/mcrcon/releases/download/v0.7.2/mcrcon-0.7.2-linux-x86-64.tar.gz"
    dest: /opt/spigot/
    owner: spigot
    group: spigot
    mode: 0740
    copy: no
  when: ansible_architecture == 'x86_64'

- name: download spigot jar
  get_url:
    url: "https://cdn.getbukkit.org/spigot/spigot-{{ spigot.version }}.jar"
    dest: /opt/spigot-{{ spigot.version }}/spigot.jar
    owner: spigot
    group: spigot
    mode: 0740
  notify:
    - restart spigot

- name: download papermc jar
  get_url:
    url: https://api.papermc.io/v2/projects/paper/versions/{{ spigot.version }}/builds/280/downloads/paper-{{ spigot.version }}-280.jar
    dest: /opt/spigot-{{ spigot.version }}/paper.jar
    owner: spigot
    group: spigot
    mode: 0740
  notify:
    - restart spigot

- name: download plugin prometheus
  get_url:
    url: "https://github.com/sladkoff/minecraft-prometheus-exporter/releases/download/v2.5.0/minecraft-prometheus-exporter-2.5.0.jar"
    dest: "/opt/spigot-{{ spigot.version }}/plugins/"
    owner: spigot
    group: spigot
    mode: 0740
  notify:
    - restart spigot

- name: push pre validate eula
  template:
    src: eula.txt.j2
    dest: "/opt/spigot-{{ spigot.version }}/eula.txt"
    mode: 0640
    owner: spigot
    group: spigot   
  notify:
    - restart spigot

- name: server properties
  template:
    src: server.properties.j2
    dest: "/opt/spigot-{{ spigot.version }}/server.properties"
    mode: 0640
    owner: spigot
    group: spigot  
  notify:
    - restart spigot

- name: config prometheus plugin
  copy:
    content: "{{ spigot.plugin_prometheus | to_nice_yaml }}"
    dest: "/opt/spigot-{{ spigot.version }}/plugins/PrometheusExporter/config.yml"
    mode: 0640
    owner: spigot
    group: spigot
  notify:
    - restart spigot

- name: Create Unit file spigot
  template:
    src: spigot.service.j2
    dest: /etc/systemd/system/spigot.service
    mode: 0640
  notify:
    - restart spigot
    - reload systemctl

- name: Start spigot
  service:
    name: spigot.service
    state: started
    enabled: yes

- name: push backup script
  template:
    src: backup_spigot.sh.j2
    dest: /opt/spigot/backup_spigot.sh
    mode: 0755

- name: save-all every hours
  cron:
    name: "save_spigot"
    state: present
    minute: "1"
    job: "/opt/spigot/mcrcon -p {{ spigot.server_properties['rcon.password'] }} save-all | logger -t save_spigot"

- name: backup every day
  cron:
    name: "backup_spigot"
    state: present
    minute: "15"
    hour: "8"
    job: "/opt/spigot/backup_spigot.sh | logger -t backup_spigot"
