---
- name: install libselinux-python binary for Ansible to work
  yum:
    name: libselinux-python
    state: present
  when: ansible_distribution in ['CentOS', 'Red Hat Enterprise Linux']

- name: install libselinux-python binary for Ansible to work
  apt:
    name: python-selinux
    state: present
  when: ansible_distribution in ['Debian', 'Ubuntu']

- name: create Prometheus group
  group:
    name: prometheus
    state: present

- name: create Prometheus user
  user:
    name: prometheus
    group: prometheus
    createhome: yes
    home: /opt/prometheus
    shell: /sbin/nologin
    comment: "Prometheus User"
    state: present

- name: mkdir for general cases
  file:
    path: "{{ item }}"
    state: directory
    owner: prometheus
    group: prometheus
    recurse: yes
    mode: 0740
  with_items:
    - /opt/blackbox_exporter
    - /etc/blackbox_exporter
    - /var/log/blackbox_exporter
    - /var/run/blackbox_exporter

- name: download gosu executable
  get_url:
    url: "https://github.com/tianon/gosu/releases/download/1.10/gosu-amd64"
    dest: "/usr/local/bin/gosu"
  when: ansible_architecture == 'x86_64'

- name: download gosu executable
  get_url:
    url: "https://github.com/tianon/gosu/releases/download/1.10/gosu-armhf"
    dest: "/usr/local/bin/gosu"
  when: ansible_architecture == 'armv7l' or ansible_architecture == 'armv6l'

- name: add executable permission
  file:
    path: "/usr/local/bin/gosu"
    state: file
    mode: "a+x"

- name: download and untar blackbox_exporter tarball
  unarchive:
    src: "https://github.com/prometheus/blackbox_exporter/releases/download/v{{ blackbox_exporter.version }}/blackbox_exporter-{{ blackbox_exporter.version }}.linux-amd64.tar.gz"
    dest: /opt/blackbox_exporter
    creates: /opt/blackbox_exporter/blackbox_exporter-{{ blackbox_exporter.version }}.linux/blackbox_exporter
    owner: prometheus
    group: prometheus
    mode: 0740
    copy: no
  when: ansible_architecture == 'x86_64'
  notify:
    - restart blackbox_exporter

- name: download and untar blackbox_exporter tarball
  unarchive:
    src: "https://github.com/prometheus/blackbox_exporter/releases/download/v{{ blackbox_exporter.version }}/blackbox_exporter-{{ blackbox_exporter.version }}.linux-armv7.tar.gz"
    dest: /opt/blackbox_exporter
    creates: /opt/blackbox_exporter/blackbox_exporter-{{ blackbox_exporter.version }}.linux/blackbox_exporter
    owner: prometheus
    group: prometheus
    mode: 0740
    copy: no
  when: ansible_architecture == 'armv7l'
  notify:
    - restart blackbox_exporter

- name: download and untar blackbox_exporter tarball
  unarchive:
    src: "https://github.com/prometheus/blackbox_exporter/releases/download/v{{ blackbox_exporter.version }}/blackbox_exporter-{{ blackbox_exporter.version }}.linux-armv6.tar.gz"
    dest: /opt/blackbox_exporter
    creates: /opt/blackbox_exporter/blackbox_exporter-{{ blackbox_exporter.version }}.linux/blackbox_exporter
    owner: prometheus
    group: prometheus
    mode: 0740
    copy: no
  when: ansible_architecture == 'armv6l'
  notify:
    - restart blackbox_exporter

- file:
    src: /opt/blackbox_exporter/blackbox_exporter-{{ blackbox_exporter.version }}.linux-amd64
    dest: /opt/blackbox_exporter/blackbox_exporter-{{ blackbox_exporter.version }}.linux
    owner: prometheus
    group: prometheus
    state: link
  when: ansible_architecture == 'x86_64'

- file:
    src: /opt/blackbox_exporter/blackbox_exporter-{{ blackbox_exporter.version }}.linux-armv7
    dest: /opt/blackbox_exporter/blackbox_exporter-{{ blackbox_exporter.version }}.linux
    owner: prometheus
    group: prometheus
    state: link
  when: ansible_architecture == 'armv7l'

- file:
    src: /opt/blackbox_exporter/blackbox_exporter-{{ blackbox_exporter.version }}.linux-armv6
    dest: /opt/blackbox_exporter/blackbox_exporter-{{ blackbox_exporter.version }}.linux
    owner: prometheus
    group: prometheus
    state: link
  when: ansible_architecture == 'armv6l'

- name: Copy blackbox configuration
  template:
    src: "{{ blackbox_exporter.configuration_template | default('blackbox_exporter.yml.j2') }}"
    dest: /etc/blackbox_exporter/blackbox_exporter.yml
    owner: prometheus
    group: prometheus
    mode: 0740
  notify:
    - restart blackbox_exporter

- name: Create Unit file blackbox_exporter
  template:
    src: blackbox_exporter.service.j2
    dest: /etc/systemd/system/blackbox_exporter.service
    mode: 0640
  notify:
    - restart blackbox_exporter
    - reload systemctl

- name: Start blackbox_exporter
  service:
    name: blackbox_exporter.service
    state: started
    enabled: yes
