---
- name: install libselinux-python binary for Ansible to work
  yum:
    name: libselinux-python
    state: present
  when: ansible_distribution in ['CentOS', 'Red Hat Enterprise Linux']

- name: install libselinux-python binary for Ansible to work
  apt:
    name: python-selinux
    state: present
  when: ansible_distribution in ['Debian', 'Ubuntu']

- name: create Prometheus group
  group:
    name: prometheus
    state: present

- name: create Prometheus user
  user:
    name: prometheus
    group: prometheus
    createhome: yes
    home: /opt/prometheus
    shell: /sbin/nologin
    comment: "Prometheus User"
    state: present

- name: mkdir for general cases
  file:
    path: "{{ item }}"
    state: directory
    owner: prometheus
    group: prometheus
    recurse: yes
    mode: 0740
  with_items:
    - /opt/haproxy_exporter
    - /etc/haproxy_exporter
    - /var/log/haproxy_exporter
    - /var/run/haproxy_exporter

- name: download gosu executable
  get_url:
    url: "https://github.com/tianon/gosu/releases/download/1.10/gosu-amd64"
    dest: "/usr/local/bin/gosu"
  when: ansible_architecture == 'x86_64'

- name: download gosu executable
  get_url:
    url: "https://github.com/tianon/gosu/releases/download/1.10/gosu-armhf"
    dest: "/usr/local/bin/gosu"
  when: ansible_architecture == 'armv7l' or ansible_architecture == 'armv6l'

- name: add executable permission
  file:
    path: "/usr/local/bin/gosu"
    state: file
    mode: "a+x"

- name: download and untar haproxy_exporter tarball
  unarchive:
    src: "https://github.com/prometheus/haproxy_exporter/releases/download/v0.9.0/haproxy_exporter-0.9.0.linux-amd64.tar.gz"
    dest: /opt/haproxy_exporter
    creates: /opt/haproxy_exporter/haproxy_exporter-0.9.0.linux/haproxy_exporter
    owner: prometheus
    group: prometheus
    mode: 0740
    copy: no
  when: ansible_architecture == 'x86_64'
  notify:
    - restart haproxy_exporter

- name: download and untar haproxy_exporter tarball
  unarchive:
    src: "https://github.com/prometheus/haproxy_exporter/releases/download/v0.9.0/haproxy_exporter-0.9.0.linux-armv7.tar.gz"
    dest: /opt/haproxy_exporter
    creates: /opt/haproxy_exporter/haproxy_exporter-0.9.0.linux/haproxy_exporter
    owner: prometheus
    group: prometheus
    mode: 0740
    copy: no
  when: ansible_architecture == 'armv7l'
  notify:
    - restart haproxy_exporter

- name: download and untar haproxy_exporter tarball
  unarchive:
    src: "https://github.com/prometheus/haproxy_exporter/releases/download/v0.9.0/haproxy_exporter-0.9.0.linux-armv6.tar.gz"
    dest: /opt/haproxy_exporter
    creates: /opt/haproxy_exporter/haproxy_exporter-0.9.0.linux/haproxy_exporter
    owner: prometheus
    group: prometheus
    mode: 0740
    copy: no
  when: ansible_architecture == 'armv6l'
  notify:
    - restart haproxy_exporter

- file:
    src: /opt/haproxy_exporter/haproxy_exporter-0.9.0.linux-amd64
    dest: /opt/haproxy_exporter/haproxy_exporter-0.9.0.linux
    owner: prometheus
    group: prometheus
    state: link
  when: ansible_architecture == 'x86_64'

- file:
    src: /opt/haproxy_exporter/haproxy_exporter-0.9.0.linux-armv7
    dest: /opt/haproxy_exporter/haproxy_exporter-0.9.0.linux
    owner: prometheus
    group: prometheus
    state: link
  when: ansible_architecture == 'armv7l'

- file:
    src: /opt/haproxy_exporter/haproxy_exporter-0.9.0.linux-armv6
    dest: /opt/haproxy_exporter/haproxy_exporter-0.9.0.linux
    owner: prometheus
    group: prometheus
    state: link
  when: ansible_architecture == 'armv6l'

- name: Create Unit file haproxy_exporter
  template:
    src: haproxy_exporter.service.j2
    dest: /etc/systemd/system/haproxy_exporter.service
    mode: 0640
  notify:
    - restart haproxy_exporter
    - reload systemctl

- name: Start haproxy_exporter
  service:
    name: haproxy_exporter.service
    state: started
    enabled: yes
