- name: install
  yum:
    name: 'sudo'
    update_cache: yes
    state: latest
  when: ansible_distribution in ['CentOS', 'Red Hat Enterprise Linux']

- name: install
  dnf:
    name: 'sudo'
    state: latest
  when: ansible_distribution in ['Fedora']

- name: install
  apt:
    name: 'sudo'
    update_cache: yes
    state: latest
  when: ansible_distribution in ['Debian', 'Ubuntu']

- group:
    name: supergroup
    state: present

- name: add groups
  group:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ groups_to_add }}"
  when: groups_to_add is defined

- name: add users
  user:
    name: "{{ item.name }}"
    createhome: yes
    state: "{{ item.state }}"
    groups: "{{ item.groups }}"
    home: "{{ item.home | default(omit) }}"
  with_items:
    - "{{ users }}"

- name: Set authorized key took from vars
  authorized_key:
    user: "{{ item.name }}"
    state: "{{ item.state }}"
    key: "{{ item.ssh_key }}"
  with_items:
    - "{{ ssh_key }}"

- name: sshd configuration file update
  copy: 
    src: sshd_config
    dest: /etc/ssh/sshd_config
    validate: '/usr/sbin/sshd -T -f %s'
    owner: root
    group: root
    mode: 0600
  notify: restart sshd

- template:
    src: sudoers.j2
    dest: /etc/sudoers
    owner: root
    group: root
    mode: 0644
