- name: Import rsyslog key
  rpm_key:
    key: http://rpms.adiscon.com/RPM-GPG-KEY-Adiscon
    state: present
    validate_certs: no
  when: ansible_distribution in ['CentOS', 'Red Hat Enterprise Linux', 'Fedora']

- name: add rsyslog repo
  yum_repository:
    name: rsyslog
    description: rsyslog
    baseurl: http://rpms.adiscon.com/v8-stable/epel-$releasever/$basearch
  when: ansible_distribution in ['CentOS', 'Red Hat Enterprise Linux', 'Fedora']

- name: Ensure Rsyslog is installed
  yum:
    name: rsyslog
    state: installed
  when: ansible_system == "Linux"

- name: Ensure Rsyslog is installed
  pkgng:
    name: rsyslog
    state: present
  when: ansible_system == "FreeBSD"

- service:
    name: rsyslog
    state: started
    enabled: yes
  when: ansible_system == "Linux"

- name: Rsyslog client configuration
  template:
    src: "client.conf.j2"
    dest: "/usr/local/etc/rsyslog.conf"
    owner: root
    group: root
    mode: 0644
  notify:
    - restart rsyslog
  when: rsyslog.type == "client" and ansible_system == "FreeBSD"

- service:
    name: syslogd
    state: stopped
    enabled: no
  when: ansible_system == "FreeBSD"

- service:
    name: rsyslogd
    state: started
    enabled: yes
  when: ansible_system == "FreeBSD"

- name: Rsyslog client configuration
  template:
    src: "client.conf.j2"
    dest: "/etc/rsyslog.conf"
    owner: root
    group: root
    mode: 0644
  notify:
    - restart rsyslog
  when: rsyslog.type == "client"

- name: Rsyslog server configuration
  template:
    src: "server.conf.j2"
    dest: "/etc/rsyslog.conf"
    owner: root
    group: root
    mode: 0644
  notify:
    - restart rsyslog
  when: rsyslog.type == "server"
