- name: Import rsyslog key
  rpm_key:
    key: http://rpms.adiscon.com/RPM-GPG-KEY-Adiscon
    state: present
    validate_certs: no
  when: ansible_distribution in ['CentOS', 'Red Hat Enterprise Linux', 'Fedora']

- name: add rsyslog repo
  yum_repository:
    name: rsyslog
    description: rsyslog
    baseurl: http://rpms.adiscon.com/v8-stable/epel-$releasever/$basearch
  when: ansible_distribution in ['CentOS', 'Red Hat Enterprise Linux', 'Fedora']

- name: Ensure Rsyslog is installed
  yum:
    name: rsyslog
    state: installed
  when: ansible_distribution in ['CentOS', 'Red Hat Enterprise Linux', 'Fedora']

- name: Ensure Rsyslog is installed
  apt:
    state: latest 
    update_cache: yes
  when: ansible_distribution in ['Debian', 'Ubuntu']

- name: Ensure Rsyslog is installed
  pkgng:
    name: rsyslog
    state: present
  when: ansible_system == "FreeBSD"

- service:
    name: rsyslog
    state: started
    enabled: yes
  when: ansible_system == "Linux"

- name: Rsyslog client configuration
  template:
    src: "client.conf.j2"
    dest: "/usr/local/etc/rsyslog.conf"
    owner: root
    group: wheel
    mode: 0644
  notify:
    - restart rsyslogd
  when: rsyslog.type == "client" and ansible_system == "FreeBSD"

- service:
    name: syslogd
    state: stopped
    enabled: no
  when: ansible_system == "FreeBSD"

- service:
    name: rsyslogd
    state: started
    enabled: yes
  when: ansible_system == "FreeBSD"

- name: Rsyslog client configuration
  template:
    src: "client.conf.j2"
    dest: "/etc/rsyslog.conf"
    owner: root
    group: root
    mode: 0644
  notify:
    - restart rsyslog
  when: rsyslog.type == "client" and ansible_system == "Linux"

- name: Rsyslog server configuration
  template:
    src: "server.conf.j2"
    dest: "/etc/rsyslog.conf"
    owner: root
    group: root
    mode: 0644
  notify:
    - restart rsyslog
  when: rsyslog.type == "server"

- name: Create a directory if it does not exist
  file:
    path: /etc/systemd/system/rsyslog.service.d
    state: directory
  when: ansible_system == "Linux"

- name: push override service rsyslog
  copy:
    src: 10-enable-syslog-socket.conf
    dest: /etc/systemd/system/rsyslog.service.d/10-enable-syslog-socket.conf
    owner: root
    group: root
    mode: 0644
  when: ansible_system == "Linux"
  notify:
    - reload systemctl
    - restart rsyslog
    - restart systemd-journald

- name: Ensure SELinux is set to enforcing mode
  lineinfile:
    path: /usr/lib/systemd/system/rsyslog.service
    regexp: '^;Alias=syslog.service$'
    line: Alias=syslog.service
  when: ansible_distribution in ['CentOS', 'Red Hat Enterprise Linux', 'Fedora']
  notify:
    - reload systemctl
    - restart rsyslog
    - restart systemd-journald

- service:
    name: rsyslog
    state: started
    enabled: yes
  when: ansible_system == "Linux"
