---
# tasks file for yum-repo
- name: install yum repo tools
  yum:
    name: 
        - createrepo
        - yum-utils
    state: installed

- name: run createrepo
  shell: createrepo /data/repo/centos/7

- name: add user data
  user:
    name: data
    createhome: yes
    state: present
    groups: data
    home: /data/repo

- name: set user permissions
  file:
    path: /data/
    owner: data
    group: data
    mode: 0755

- name: set user permissions
  file:
    path: /data/repo
    owner: data
    group: data
    recurse: True
    mode: 0740

- name: Set authorized key took from vars
  authorized_key:
    user: data
    state: "{{ item.state }}"
    key: "{{ item.ssh_key }}"
  with_items:
    - "{{ yum_repo.ssh_key }}"
