---
# tasks file for yum-repo
- name: install yum repo tools
  yum:
    name: 
        - createrepo
        - yum-utils
    state: installed


- name: run createrepo
  shell: createrepo /data/repo/centos/7

- name: set user permissions
  file:
    path: /data/
    owner: data
    group: data
    recurse: True
    mode: 0770
