- name: create directory for PEM files
  file:
    path: /etc/haproxy/ssl
    owner: root
    group: root
    mode: 0600
    state: directory

- name: Copy pem files
  template:
    dest: "/etc/haproxy/ssl/{{ item.name }}.pem"
    src: ssl.pem.j2
    owner: root
    group: root
    mode: 0600
  with_items:
    - "{{ pem }}"
  notify: restart haproxy
