- name: Install ufw
  apt: 
    name: ufw 
    state: latest 
    update_cache: yes

- name : Enable ufw service
  service:
    name: ufw
    enabled: yes
    state: started

- name: Enable ufw and grant 22
  ufw:
    state: enabled
    rule: allow
    port: 22
    proto: tcp
