---
- name: reload systemctl
  command: systemctl daemon-reload

- name: restart prometheus
  service:
    name: prometheus
    state: restarted

- name: restart prometheus
  service:
    name: prometheus
    state: reloaded
