---
- name: "10s delay while starting Jenkins"
  wait_for:
    host: localhost
    port: "8080"
    delay: "10"
  when: jenkins_install.changed

- name: "Create Jenkins CLI destination directory: {{ jenkins.dest }}"
  file:
    path: "{{ jenkins.dest }}"
    state: directory

- name: Get Jenkins CLI
  get_url:
    url: "{{ jenkins.api_url }}jnlpJars/jenkins-cli.jar"
    dest: "{{ jenkins.cli_dest }}"
    mode: 0440
  register: jenkins_local_cli
  until: "'OK' in jenkins_local_cli.msg or 'file already exists' in jenkins_local_cli.msg"
  retries: 5
  delay: 10
