---

- name: Import jenkins key
  rpm_key:
    key: https://jenkins-ci.org/redhat/jenkins-ci.org.key
    state: present
    validate_certs: no

- name: Get jenkins repo for ansible
  get_url:
    url: http://pkg.jenkins-ci.org/redhat/jenkins.repo
    dest: /etc/yum.repos.d/jenkins.repo

- name: Install RedHat dependencies
  yum:
    name: "{{ item }}"
    state: latest
  with_items: "{{ jenkins.dependencies }}"

- name: Install Jenkins for RedHat
  yum:
    name: jenkins
    state: latest
  register: jenkins_install

- name: Ensure jenkins is running and starting on boot
  service:
    name: jenkins
    state: started
    enabled: yes

- import_tasks: cli.yml

- import_tasks: config.yml

- import_tasks: user.yml

- import_tasks: plugins.yml

- import_tasks: groovy_config.yml

- import_tasks: seed.yml

- import_tasks: slaves.yml
