---
- name: wait_jenkins
  shell: |
    NEXT_WAIT_TIME=0
    until {{ jenkins_wait_cli_cmd }} || [ $NEXT_WAIT_TIME -eq 10 ]; do
      sleep $(( NEXT_WAIT_TIME++ ))
    done

- name: copy Groovy script for admin account
  template:
    src: seed.groovy.j2
    dest: /tmp/seed.groovy
    owner: root
    group: root
    mode: 0600

- name: Update Admin account
  shell: "{{ jenkins_cli_cmd }} groovy /tmp/seed.groovy"

- file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /tmp/seed.groovy
